name: First Workflow # Github Action Name - Workflow Name
on : [push] # Event Trigger

jobs:
  run-shell-commands : # First Job
    runs-on : ubuntu-latest
    steps :
      - name : echo a string
        run : echo "Hello Github Actions"
      - name : Multiline command
        run  : |
          node -v
          npm -v

  parallel-job-macos : # Second Job
    runs-on : macos-latest
    steps :
      - name : echo mac version
        run : sw_vers

  dependendant-job : # Dependent Job which depends on First Job
    runs-on : ubuntu-latest
    needs : run-shell-commands
    steps :
      - name : echo os name
        run : uname -a
